import { PropertyDetail, PropertySummary, Project, Service, Testimonial } from "./types";

// This fixture data mirrors backend/seed/seed.sql. It is used only when the API
// is unreachable (e.g. viewing the frontend before the backend/DB is running),
// so reviewers see a populated site immediately. Once NEXT_PUBLIC_API_BASE_URL
// points at a live backend, all of this is bypassed automatically.

export const FALLBACK_PROPERTIES: PropertySummary[] = [
  {
    id: "1",
    reference_code: "DHR-L-0001",
    title: "Prime Residential Land in Gampaha",
    slug: "prime-residential-land-gampaha",
    category: "LAND",
    listing_type: "SALE",
    status: "PUBLISHED",
    is_featured: true,
    short_description: "A well-located 20-perch residential block with clear deed and full road access.",
    price_lkr: 8500000,
    price_on_request: false,
    price_unit: "TOTAL",
    land_extent_perches: 20,
    city_name: "Gampaha",
    district_name: "Gampaha",
    cover_url: "/images/projects/layered-edge/1.webp",
  },
  {
    id: "2",
    reference_code: "DHR-H-0001",
    title: "Modern Two-Storey House in Kandy",
    slug: "modern-two-storey-house-kandy",
    category: "HOUSE",
    listing_type: "SALE",
    status: "PUBLISHED",
    is_featured: true,
    short_description: "A modern 4-bedroom two-storey house with mountain views and secure parking.",
    price_lkr: 42000000,
    price_on_request: false,
    price_unit: "TOTAL",
    built_area_sqft: 2800,
    bedrooms: 4,
    bathrooms: 3,
    city_name: "Kandy",
    district_name: "Kandy",
    cover_url: "/images/projects/kandy-layered-edge/1.png",
  },
  {
    id: "3",
    reference_code: "DHR-H-0002-R",
    title: "Furnished House for Rent in Colombo 05",
    slug: "furnished-house-rent-colombo-05",
    category: "HOUSE",
    listing_type: "RENT",
    status: "PUBLISHED",
    is_featured: false,
    short_description: "Fully furnished 3-bedroom house for rent, close to schools and amenities.",
    price_lkr: 185000,
    price_on_request: false,
    price_unit: "PER_MONTH",
    built_area_sqft: 2200,
    bedrooms: 3,
    bathrooms: 2,
    city_name: "Colombo 05",
    district_name: "Colombo",
    cover_url: "/images/projects/homagama-two-storey/1.png",
  },
  {
    id: "4",
    reference_code: "DHR-C-0001-R",
    title: "Commercial Space for Rent in Colombo 03",
    slug: "commercial-space-rent-colombo-03",
    category: "COMMERCIAL",
    listing_type: "RENT",
    status: "PUBLISHED",
    is_featured: true,
    short_description: "Ground-floor commercial unit suited to retail or a showroom, prime frontage.",
    price_lkr: 450000,
    price_on_request: false,
    price_unit: "PER_MONTH",
    built_area_sqft: 3200,
    city_name: "Colombo 03",
    district_name: "Colombo",
    cover_url: "/images/projects/etisalat/1.png",
  },
];

export const FALLBACK_PROPERTY_DETAIL: Record<string, PropertyDetail> = Object.fromEntries(
  FALLBACK_PROPERTIES.map((p) => [
    p.slug,
    {
      ...p,
      description:
        "Full property description will appear here once content is published from the admin CMS. This listing was seeded for local development and demonstration purposes.",
      is_negotiable: p.listing_type === "SALE",
      show_exact_location: false,
      latitude: 7.0,
      longitude: 80.0,
      view_count: 128,
      province_name: "Western",
      district_name: p.district_name ?? "",
      city_name: p.city_name ?? "",
      images: [{ id: "img1", url: p.cover_url ?? "", alt_text: p.title, is_cover: true }],
      documents: [],
      amenities: [],
    } as PropertyDetail,
  ])
);

export const FALLBACK_SERVICES: Service[] = [
  {
    id: "s1",
    slug: "civil-construction",
    title: "Civil Construction",
    summary: "Residential, commercial and industrial construction from foundation to finish — delivered by Dhara's in-house engineering teams.",
    body: "Dhara manages the complete civil construction lifecycle: site preparation, substructure, superstructure, finishing and handover. Our teams are experienced across a wide range of project types — single-family residences, multi-unit developments, commercial buildings and industrial facilities throughout Sri Lanka.\n\nWe self-perform the critical trades (formwork, concrete, masonry, waterproofing) and coordinate specialist sub-contractors through a structured quality and programme management framework, giving clients a single accountable point of contact from ground-breaking to handover.\n\nKey capabilities:\n• Reinforced-concrete framed structures\n• Load-bearing masonry construction\n• Site drainage, retaining walls and earthworks\n• Waterproofing and protective coatings\n• Project management and site supervision",
    icon: "construction",
    hero_image: "/images/services/consulting1.webp",
    sort_order: 1,
  },
  {
    id: "s2",
    slug: "tower-foundations",
    title: "Tower Foundations & Substructures",
    summary: "Specialist foundation and substructure engineering for telecom towers, utility pylons and industrial structures across Sri Lanka.",
    body: "Dhara has delivered foundation and substructure packages for telecom operators, electricity transmission authorities and industrial clients. Our engineers carry out site investigation, foundation design and construction for self-supporting towers, guyed-mast structures and monopoles in challenging terrain.\n\nWe work to relevant IEC, TIA and local standards and maintain close coordination with tower OEMs to ensure anchor bolt patterns, base-plate details and grouting specifications are met precisely.\n\nKey capabilities:\n• Spread, pad and raft foundations for lattice and monopole towers\n• Driven and bored pile foundations in poor ground\n• Geosynthetic reinforcement solutions for embankments and slopes\n• Road safety and access track construction at remote sites\n• Survey, setting-out and as-built documentation",
    icon: "tower",
    hero_image: "/images/services/RoadSafety.webp",
    sort_order: 2,
  },
  {
    id: "s3",
    slug: "architectural-design",
    title: "Architectural & Structural Design",
    summary: "Concept-to-construction architectural and structural design, from initial brief through statutory approvals and construction drawings.",
    body: "Dhara's design team handles the full architectural and structural design scope in-house — concept design, planning approval drawings, statutory submissions to the local authority, structural calculations and construction issue drawings.\n\nWorking from an owner-developer perspective means our designs are tested against real build costs and construction sequences from day one. We use AutoCAD, Revit and 3D visualisation tools so clients can review their project before a single brick is laid.\n\nKey capabilities:\n• Residential, commercial and mixed-use architectural design\n• Structural engineering for RC frames and steel structures\n• Local authority submission and approval management\n• Bill of quantities linked to design milestones\n• 3D visualisation and client presentation packages",
    icon: "design",
    hero_image: "/images/services/ArchitecturalDesign.webp",
    sort_order: 3,
  },
  {
    id: "s4",
    slug: "mep",
    title: "MEP Systems",
    summary: "Mechanical, electrical and plumbing engineering — design, supply, installation and commissioning for residential and commercial buildings.",
    body: "Dhara's MEP division covers the full scope of building services engineering from schematic design through to commissioning and handover documentation. We self-perform electrical and plumbing installations and partner with specialist suppliers for HVAC and fire systems.\n\nAll electrical work is carried out by licensed electrical engineers and registered wiremen in accordance with the Sri Lanka Standards Institution (SLSI) electrical code.\n\nKey capabilities:\n• Electrical distribution, lighting and power systems\n• Plumbing, drainage and rainwater harvesting\n• Air conditioning — split systems, VRF and central plant\n• Home automation and structured cabling\n• Solar PV grid-tie and off-grid systems\n• Fire detection and suppression systems",
    icon: "mep",
    hero_image: "/images/services/homenetworking.webp",
    sort_order: 4,
  },
  {
    id: "s5",
    slug: "interiors",
    title: "Interior Design & Fit-Outs",
    summary: "Interior design and turnkey fit-outs for residential, hospitality and commercial spaces — from concept boards to final styling.",
    body: "Dhara's interior team works alongside the architectural team from the early design stages so that structural provisions, MEP rough-ins and finishing schedules are coordinated before construction begins. This eliminates the abortive work that commonly inflates budgets when interior design is treated as an afterthought.\n\nWe supply and install flooring, wall finishes, joinery, ceiling systems, sanitary ware, kitchen fittings and soft furnishings through a managed procurement model that gives clients transparent pricing and quality assurance.\n\nKey capabilities:\n• Space planning and concept design\n• Material and finish specification\n• Custom joinery and built-in furniture\n• Flooring — porcelain, hardwood, vinyl and polished concrete\n• Feature wall finishes and protective coatings\n• Kitchen and bathroom fit-out packages",
    icon: "interior",
    hero_image: "/images/services/flooring.webp",
    sort_order: 5,
  },
  {
    id: "s6",
    slug: "boq-estimation",
    title: "BOQ & Cost Auditing",
    summary: "Bill of quantities preparation, independent cost auditing and contract administration for construction projects of all scales.",
    body: "Accurate quantity surveying underpins every successful construction project. Dhara provides independently prepared Bills of Quantities (BOQ) based on standard measurement rules, enabling fair competitive tendering and transparent cost control throughout the project lifecycle.\n\nOur cost auditing service is used by building owners, financial institutions and project funders to verify contractor claims, assess cost-to-completion and identify potential budget overruns early.\n\nKey capabilities:\n• Pre-tender BOQ preparation (substructure, superstructure, finishes, external works)\n• Tender evaluation and contractor comparison reports\n• Interim payment certificate verification\n• Variation order assessment and negotiation\n• Final account preparation\n• Independent cost audits for financiers and owners",
    icon: "boq",
    hero_image: "/images/services/BOQ.webp",
    sort_order: 6,
  },
  {
    id: "s7",
    slug: "3d-visualization",
    title: "3D Visualisation & Walkthroughs",
    summary: "Photoreal 3D exterior and interior visualisations, animated walkthroughs and virtual site tours — helping clients see their project before it is built.",
    body: "Dhara produces high-quality 3D visualisations and animated walkthroughs that allow clients, investors and approval bodies to fully understand a design before construction begins. Visualisations are produced directly from the architectural model, ensuring spatial accuracy and consistency with construction drawings.\n\nOur renders are used in planning submissions, investor presentations, marketing brochures and sales launches — and are regularly updated as the design evolves.\n\nKey capabilities:\n• Exterior day and dusk renders with accurate site context\n• Interior renders with lighting simulation\n• Animated 360° walkthroughs\n• Virtual reality (VR) headset exports\n• Site plan and aerial perspective renders\n• Phased visualisations for staged developments",
    icon: "3d",
    hero_image: "/images/services/3Ddesign.webp",
    sort_order: 7,
  },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "p1",
    slug: "layered-edge",
    title: "Layered Edge Residence",
    sector: "Residential",
    location: "Colombo",
    year_completed: 2024,
    cover_image: "/images/projects/layered-edge/1.webp",
    is_featured: true,
    description: "A contemporary two-storey residence defined by bold horizontal layering, cantilevered volumes and a carefully considered relationship between interior space and landscape. Dhara delivered the full scope — architectural design, structural engineering, civil works, MEP and interiors.",
    gallery_images: [
      "/images/projects/layered-edge/1.webp",
      "/images/projects/layered-edge/2.webp",
      "/images/projects/layered-edge/3.webp",
      "/images/projects/layered-edge/4.png",
      "/images/projects/layered-edge/5.png",
      "/images/projects/layered-edge/6.png",
    ],
  },
  {
    id: "p2",
    slug: "kandy-layered-edge",
    title: "Kandy Layered Edge",
    sector: "Residential",
    location: "Kandy",
    year_completed: 2024,
    cover_image: "/images/projects/kandy-layered-edge/1.png",
    is_featured: true,
    description: "Set into the hillside topography of Kandy, this layered-edge residence steps down the natural gradient to maximise views across the valley. The design incorporates extensive reinforced concrete retaining structures, cantilevered terraces and a warm material palette of exposed concrete, timber and natural stone.",
    gallery_images: [
      "/images/projects/kandy-layered-edge/1.png",
      "/images/projects/kandy-layered-edge/2.png",
      "/images/projects/kandy-layered-edge/3.png",
      "/images/projects/kandy-layered-edge/4.png",
      "/images/projects/kandy-layered-edge/5.png",
      "/images/projects/kandy-layered-edge/6.png",
      "/images/projects/kandy-layered-edge/7.png",
      "/images/projects/kandy-layered-edge/8.png",
      "/images/projects/kandy-layered-edge/9.png",
    ],
  },
  {
    id: "p3",
    slug: "homagama-two-storey",
    title: "Homagama Two-Storey Residence",
    sector: "Residential",
    location: "Homagama",
    year_completed: 2023,
    cover_image: "/images/projects/homagama-two-storey/1.png",
    is_featured: true,
    description: "A clean-lined two-storey family residence in Homagama, delivered on a compact suburban plot. The design prioritises natural ventilation and light while maximising the floor-plate area within planning constraints. Dhara provided architectural design, structural engineering and full construction including MEP and finishes.",
    gallery_images: [
      "/images/projects/homagama-two-storey/1.png",
      "/images/projects/homagama-two-storey/2.png",
      "/images/projects/homagama-two-storey/3.png",
      "/images/projects/homagama-two-storey/4.png",
      "/images/projects/homagama-two-storey/5.png",
      "/images/projects/homagama-two-storey/6.png",
    ],
  },
  {
    id: "p4",
    slug: "fire-installation",
    title: "Fire Suppression Installation",
    sector: "Industrial",
    location: "Colombo",
    year_completed: 2023,
    cover_image: "/images/projects/fire-installation/1.png",
    is_featured: true,
    description: "Design, supply and installation of a complete wet-pipe sprinkler and gaseous suppression system for a multi-floor commercial facility. The project included hydraulic design, pipe fabrication and installation, pump-set commissioning, control panel integration and authority sign-off.",
    gallery_images: [
      "/images/projects/fire-installation/1.png",
      "/images/projects/fire-installation/2.png",
      "/images/projects/fire-installation/3.png",
      "/images/projects/fire-installation/4.png",
      "/images/projects/fire-installation/5.png",
      "/images/projects/fire-installation/6.png",
      "/images/projects/fire-installation/7.png",
      "/images/projects/fire-installation/8.png",
      "/images/projects/fire-installation/9.png",
      "/images/projects/fire-installation/10.png",
    ],
  },
  {
    id: "p5",
    slug: "etisalat-tower",
    title: "Etisalat Tower Foundation",
    sector: "Infrastructure",
    location: "Western Province",
    year_completed: 2023,
    cover_image: "/images/projects/etisalat/1.png",
    is_featured: true,
    description: "Foundation engineering and civil works for a self-supporting telecom tower for Etisalat (now Hutch) Sri Lanka. The scope included site investigation, foundation design to TIA-222 standard, mass-concrete pad construction, anchor bolt installation, earthing system and access road formation.",
    gallery_images: [
      "/images/projects/etisalat/1.png",
      "/images/projects/etisalat/2.png",
      "/images/projects/etisalat/3.png",
      "/images/projects/etisalat/4.png",
    ],
  },
  {
    id: "p6",
    slug: "electric-tower",
    title: "Electric Transmission Tower Foundation",
    sector: "Infrastructure",
    location: "Sri Lanka",
    year_completed: 2022,
    cover_image: "/images/projects/electric-tower/1.png",
    is_featured: false,
    description: "Civil foundation works for electricity transmission tower structures on behalf of the Ceylon Electricity Board. The project involved setting-out in steep terrain, excavation, reinforced concrete foundation construction, backfill compaction and stub-angle installation to tight angular tolerances.",
    gallery_images: [
      "/images/projects/electric-tower/1.png",
      "/images/projects/electric-tower/2.png",
      "/images/projects/electric-tower/3.png",
      "/images/projects/electric-tower/4.png",
    ],
  },
  {
    id: "p7",
    slug: "petroleum-tank",
    title: "Petroleum Tank Civil Works",
    sector: "Industrial",
    location: "Sri Lanka",
    year_completed: 2022,
    cover_image: "/images/projects/petroleum-tank/1.png",
    is_featured: false,
    description: "Civil engineering works for above-ground petroleum storage tanks, including bunded containment foundations, fire-water ring-main trenching, hardstand paving and drainage systems. All work was carried out to applicable fire and petroleum authority standards.",
    gallery_images: [
      "/images/projects/petroleum-tank/1.png",
      "/images/projects/petroleum-tank/2.png",
      "/images/projects/petroleum-tank/3.png",
      "/images/projects/petroleum-tank/4.png",
    ],
  },
];

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    author_name: "K. Perera",
    author_location: "Colombo",
    quote: "Dhara delivered our home exactly on schedule and on budget. The attention to detail — from the structural work right through to the final finishes — was outstanding. We would not hesitate to recommend them.",
    rating: 5,
  },
  {
    id: "t2",
    author_name: "S. Fernando",
    author_location: "Galle",
    quote: "Professional team from the survey stage right through to handover. Their BOQ was accurate to within 2% of the final cost, which made financing the project straightforward. Excellent communication throughout.",
    rating: 5,
  },
  {
    id: "t3",
    author_name: "N. Wickramasinghe",
    author_location: "Kandy",
    quote: "Clear communication and honest advice throughout our land purchase and subsequent design-and-build. The 3D visualisations they produced gave us real confidence in the design before any concrete was poured.",
    rating: 5,
  },
  {
    id: "t4",
    author_name: "R. Jayasinghe",
    author_location: "Negombo",
    quote: "Dhara handled our telecom tower foundation project professionally and completed it three days ahead of schedule despite difficult site conditions. The quality of the concrete work and the accuracy of the stub-angle setting-out was first class.",
    rating: 5,
  },
  {
    id: "t5",
    author_name: "P. Dissanayake",
    author_location: "Colombo",
    quote: "We engaged Dhara for an independent cost audit of our commercial development. Their report was thorough, clearly written and identified cost overruns we had not spotted. Saved us a significant sum.",
    rating: 5,
  },
];
